config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
   devise_for :users, controllers: {
         sessions: 'users/sessions'
       }

   # get 'comments/index'
   # get 'comments/show'
   # get 'comments/edit'
  # get 'posts/index'
  # get 'posts/show'
  # get 'posts/new'
  # get 'posts/edit'
  # get 'posts/destroy'
  # get 'users/index'
  # get 'users/show'
  # get 'users/edit'
  # get 'users/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts
  resources :users
  resources :comments

  root 'users#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post 
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation, :fname, :lname, :username])
    end
  end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to post_path(params[:comment][:post_id])
  end
end

  def destroy
  end

  private
    def comment_params
      params.require(:comment).permit(:content, :post_id)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments

  end

  def edit
    @post = Post.find(params[:id])
  end


def destroy
  @post = Post.find(params[:id])
  @post.destroy
  redirect_to user_path
end

  def update
  @post = Post.find(params[:id])
  @post.update(post_params)
  @post.save
  redirect_to post_path(@post)
end

  private
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    p params
    p current_user
    if !current_user
      redirect_to new_user_session_path
    elsif params[:id].nil?
      @user = current_user
    else
      @user = User.find(params[:id])
  end
end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    @user.save
    redirect_to user_path(@user)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to new_user_session_path
  end

  private
    def user_params
      params.require(:user).permit(:fname, :lname, :username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bees Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Crimson+Text|Montserrat|Merriweather" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class = "container navbar">
      <nav>
        <% if current_user %>
          <%= link_to 'Home', root_path %>
          <%= link_to 'Creat Post', new_post_path %>
          <%= link_to 'All Posts', posts_path %>
          <%= link_to 'All Users', users_path %>
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
        <%end%>
      </nav>
  </div>

    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class = "container" >
  <% if current_user.id == @post.user.id %>
  <%= form_for @post do |f| %>
    <%= f.label :title, "Title: " %>
    <%= f.text_field :title %>
    <br>
    <%= f.label :content, "Content: " %>
    <%= f.text_field :content %>
    <br>
    <%= f.submit %>
  <% end %>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class = "container" >
  <% @posts.each do |post| %>
    <p>Title: <%= link_to post.title, post_path(post) %></p>
    <p>Content: <%= post.content %></p>
    <hr>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>new post</h1>

<div class = "container" >
  <%= form_for @post do |f| %>
    <%= f.label :title, "Title:"%><br />
    <%= f.text_area :title %>
    <br>
    <%= f.label :content, "Content:"%><br />
    <%= f.text_area :content%>
    <br>
    <%= f.submit %>
  <%end%>
</div>  

app/views/posts/show.html.erb
<div class = "container" >
  <% if current_user.id == @post.user.id %>

   <%= link_to "Edit Post", edit_post_path(@post) %>
   <%= link_to "Delete Post", post_path(@post), method: :delete %>
 <% end %>
  <div>
    <p>Title: <%= @post.title %></p>
    <p>Content: <%= @post.content %></p>
  </div>

  <%= form_for Comment.new do |f| %>
  <%= hidden_field_tag "[comment]post_id", @post.id %>
      <p>Comment: </p>
  <%= f.text_area :content %>
  <%= f.submit "Submit" %>
  <%end%>

  <div>
    <% @comments.each do |comment| %>
      <p><% comment.user.fname %></p>
      <p>Comment: <%= comment.content %></p>
      <hr>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class = "container" >
  <%= form_for @user do |f| %>
    <%= f.label :fname, "First name: " %>
    <%= f.text_field :fname %>
    <br>
    <%= f.label :lname, "Last name: " %>
    <%= f.text_field :lname %>
    <br>
    <%= f.label :username, "Username: " %>
    <%= f.text_field :username %>
    <br>
    <%= f.submit %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class = "container" >
  <% @users.each do |user| %>
    <p>First Name: <%= link_to user.fname, user_path(user) %></p>
    <p>Last Name: <%= user.lname %></p>
    <p>Username: <%= user.username %></p>
  <% end %>
</div>

app/views/users/show.html.erb
<div class = "container" >
  <% if current_user.id %>
  <p>Your Profile</p>
  <p>First name: <%= @user.fname %></p>
  <p>Last name: <%= @user.lname %></p>
  <p>Username: <%= @user.username %></p>
  <%end%>

  <% if @user.id == current_user.id %>
    <%= link_to "Edit Profile", edit_user_path(@user) %>
    <%= link_to 'Delete Profile', user_path(@user), :method => :delete, data: {confirm: "Are you sure?"} %>
  <%end%>
</div>